modLoader="javafml"
loaderVersion="[35,)"
license="GNU GPL V3"
issueTrackerURL="https://discord.gg/pHren9yxzW"
logoFile="logo.png"
[[mods]]
modId="relics"
version="0.4.1.8"
displayName="Relics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/relics-mod"
authors="SSKirillSS"
description="Just a mod about useful relics with unique mechanics ;)"
[[dependencies.relics]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.52,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.relics]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="AFTER"
    side="BOTH"