modLoader="javafml"
loaderVersion="[35,)"
license="GNU GPL V3"
issueTrackerURL="https://discord.gg/pHren9yxzW"
[[mods]]
modId="relics"
version="0.1.6"
displayName="Relics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/relics-mod"
authors="SSKirillSS"
description="Just a mod about useful relics with unique mechanics ;)"
[[dependencies.relics]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.relics]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.4-4.0.3.5,)"
    ordering="AFTER"
    side="BOTH"