modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"
issueTrackerURL = "https://discord.gg/pHren9yxzW"
logoFile = "logo.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/relics-mod"
authors = "${mod_authors}"
description = '''Just a mod about useful relics with unique mechanics ;)'''

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type="required"
    versionRange = "[1.21, 1.22)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "neoforge"
    type="required"
    versionRange = "[21.0.10-beta,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "curios"
    type="required"
    versionRange = "[9.0.0+1.21,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "octolib"
    type="required"
    versionRange = "[0.3,)"
    ordering = "NONE"
    side = "BOTH"